<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Family" failures="0" tests="3" name="runners.RetryCucumberRunner" time="76.196" errors="1" timestamp="2025-06-15T20:06:45 IST" skipped="0">
  <testcase classname="runners.RetryCucumberRunner" name="runScenario" time="20.949"/>
  <testcase classname="runners.RetryCucumberRunner" name="runScenario" time="34.261">
    <error message="java.lang.NullPointerException: Cannot invoke &quot;com.aventstack.extentreports.ExtentTest.info(String)&quot; because the return value of &quot;utils.ExtentManager.getTest()&quot; is null" type="java.util.concurrent.CompletionException">
      <![CDATA[java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.info(String)" because the return value of "utils.ExtentManager.getTest()" is null
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.info(String)" because the return value of "utils.ExtentManager.getTest()" is null
at utils.RetryAnalyzer.retry(RetryAnalyzer.java:15)
at org.testng.internal.invokers.TestInvoker.shouldRetryTestMethod(TestInvoker.java:555)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:726)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
... 3 more
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="runners.RetryCucumberRunner" name="runScenario" time="20.986"/>
</testsuite> <!-- runners.RetryCucumberRunner -->
